### ISSUE TITLE
Skip serialization of `Option::None` fields

### ISSUE THREAD

**Issue by manuelmauro** [manuelmauro/algonaut#10]
Currently many structs in the client libraries (algod, kmd, indexer) serialize None fields. Add the proper macro directive from serde to such fields, checking the official Algorand documentation, adding and running tests.
```
#[serde(skip_serializing_if = "Option::is_none")]
```

**Comment by epequeno** [comment]
I'd like to pick this one up. Can you provide examples of how to test if serialization is happening properly?

**Comment by manuelmauro** [comment]
Hi! I thought that instead of adding tests we can use this reference implementation https://github.com/manuelmauro/algorand-oas-generated-v2-clients
