### ISSUE TITLE
Compile-time validation on builders

### ISSUE THREAD

**Issue by manuelmauro** [manuelmauro/algonaut#109]
The current builders are minimal implementations of the pattern that do not apply any compile-time validation. This crate offers a solution to this problem https://crates.io/crates/typed-builder while suffering from some limitations.

**Comment by ivanschuetz** [comment]
Bringing up here again that this:

> The current builders are minimal implementations of the pattern that do not apply any compile-time validation

is outdated. Our transaction builders were refactored to check for mandatory fields at compile time. The only remaining builders with the issue should be the algod/kmd/indexer builders, which have a total of 1 or 2 mandatory fields. Here we might need possibly just a factory (initializer that returns an error if e.g. the URL is incorrectly formatted) instead of the builder pattern.

**Comment by AlterionX** [comment]
A slight suggestion: I think the default builder should just be a tight wrapper of the custom endpoint builder struct. Reasoning being -- creating a custom endpoint should be a strictly more powerful ability than creating the default endpoint. It might also help with the discovery of the custom endpoint builder.

**Comment by ivanschuetz** [comment]
What about something like this:

```rust
#[derive(Default)]
pub struct AlgodBuilder {}

impl AlgodBuilder {
    pub fn with_token(url: &str, token: &str) -> Result<v2::Algod, AlgonautError> {
        Self::with_headers(
            url,
            vec![("X-Algo-API-Token", &ApiToken::parse(token)?.to_string())],
        )
    }

    pub fn with_headers(url: &str, headers: Headers) -> Result<v2::Algod, AlgonautError> {
        Ok(v2::Algod::new(algonaut_client::algod::v2::Client::new(
            url, headers,
        )?))
    }
}
```

We could also remove `AlgodBuilder` and just add a convenience initializer to `Algod` with the token.

The later would also simplify managing multiple versions - if there are new versions, we don't need to create multiple entry points / builders.

If the initialization becomes more complex later (unlikely?) we can consider re-adding the builder pattern. Currently it seems not justified.
