### ISSUE TITLE
Consider splitting `message.rs` modules in `message.rs` and `models.rs`

### ISSUE THREAD

**Issue by manuelmauro** [manuelmauro/algonaut#11]
While messages are convenient structs encoding HTTP requests and responses models are working structs that are meant to be used from the end user of the SDK.

**Comment by i-schuetz** [comment]
This task needs to be updated. Are we going to add separate domain objects everywhere, like we did for `Transaction`?

**Comment by manuelmauro** [comment]
It seems like a good solution to me, while I find the current organization ambiguous.
