### ISSUE TITLE
Remove algod v1

### ISSUE THREAD

**Issue by ivanschuetz** [manuelmauro/algonaut#110]
- Purestake [discontinued v1 almost a year ago](https://developer.purestake.io/v1deprecation)
- AlgoExplorer [doesn't support it anymore](https://dev.algoexplorer.io/api-dev/v1)
- Devs using a Rusk community SDK seems more on the "bleeding edge" side of things so should be unlikely to be working with or in teams using an archaic node api.
- As indicated in the readme, our APIs can still be considered WIP, which implies less commitment to maintaining backwards compatibility.

**Comment by dash2507** [comment]
@ivanschuetz  I would like to work on this issue.

**Comment by ivanschuetz** [comment]
Great, assigned!
