### ISSUE TITLE
`MicroAlgos::to_algos` and `MicroAlgos::from_algos` are imprecise.

### ISSUE THREAD

**Issue by AlterionX** [manuelmauro/algonaut#135]
**Describe the bug**
Floats are imprecise due to their format, and should never be used for storing financially sensitive data.

**To Reproduce**
Not sure about the exact maths but:
```rs
let off_by_one = MicroAlgos::from_algos(MicroAlgos(1).to_algos() * 5e4); // this is MicroAlgos(49999), probably
```

**Expected behavior**
```rs
assert!(MicroAlgos::from_algos(MicroAlgos(1).to_algos() * 5e4) == MicroAlgos(50000))
```

**Additional context**
I'd look at `num::Rational` for this. But not sure how that would impact build sizes. I haven't tried it, been busy.

If the intent is an easy way to print MicroAlgos, a custom implementation of `Display` would suffice. Not too sure what the conversion is for, actually...

Coming to think of it, `from_algos` should probably act as `FromStr` does for malformed inputs.

**Comment by manuelmauro** [comment]
Considering the approach of the official Java SDK, we could opt for num::BigInt and num::BigRational https://algorand.github.io/java-algorand-sdk/com/algorand/algosdk/util/AlgoConverter.html#toMicroAlgos(java.math.BigDecimal)

**Comment by ivanschuetz** [comment]
I'm using [rust_decimal](https://github.com/paupino/rust-decimal) in my projects. I lean towards removing these conversions from the SDK, as it's a UI thing (and it's not being used anywhere in the SDK).

**Comment by AlterionX** [comment]
It's also a bit useful for parsing user input if it works right.

But I'm not opposed to removing it, haha.

What's the difference between `rust_decimal` and `num::BigRational`? Just curious.

**Comment by ivanschuetz** [comment]
Haven't used `num::BigRational`. I think that I just found `rust_decimal` first or preferred that it seemed more actively maintained.

This leads to another reason for removing this: it's better to let users choose what to use. There are project specific requirements like WASM compatibility, binary size, performance.. The benefit of supporting this is tiny, while we're taking a relatively high cost integrating a new dependency, and it might not be optimal for everyone.

**Comment by manuelmauro** [comment]
I am also OK with removing them, but what about  'MicroAlgos`'s type? It is currently implemented as a  'u64`, doesn't this raise possible safety concerns?

**Comment by ivanschuetz** [comment]
> `MicroAlgos`'s

`u64` should be fine as this is what's used everywhere in the API. You maybe mean the unchecked arithmetic operations (this should be improved)?

**Comment by manuelmauro** [comment]
Yes, you're definitely right. `u64` seems enough in terms of range of values, given that we implement checks on the arithmetic of `MicroAlgos`.

**Comment by ivanschuetz** [comment]
The problem is that we don't do that, e.g: https://github.com/manuelmauro/algonaut/blob/0d93ce108d66a593ccc0840c0e9bca6dee795e3c/algonaut_core/src/lib.rs#L45

**Comment by AlterionX** [comment]
I'm not sure we should. We could perhaps create methods for checked versions of add/sub/mul/div? But we also wouldn't want to force the user to run those checks if this code is on a hot loop of some sort.

Sidenote: the Add impl for u64's panics in debug but doesn't in release.

**Comment by ivanschuetz** [comment]
I agree that we should offer both variants.

> Sidenote: the Add impl for u64's panics in debug but doesn't in release.

On release mode it silently overflows, which in most cases is worse. Checked operations also prevent e.g. panicking on division by zero.
