### ISSUE TITLE
Failed to parse response for the `blocks` endpoint from indexer.

### ISSUE THREAD

**Issue by AlterionX** [manuelmauro/algonaut#138]
**Describe the bug**
Indexer thinks that a response from the `blocks` endpoint is malformed when it's not.

**To Reproduce**
```rust
indexer = Indexer::
indexer.block(Round(19566971)).expect("everything to be fine")
```

**Expected behavior**
The response from `https://algoindexer.algoexplorerapi.io/v2/blocks/19566971` to get parsed without an issue.

**Additional context**
Haven't tried this on master yet, I'm on a tweaked fork of algonaut.
I think, more specifically, algonaut coughs when processing `"lease":"Hj34NGm7otoqJJtatuHCJim6Lrp8pPCcupYUwY7iVKE="`.

Possibly related to #98 ?

**Comment by ivanschuetz** [comment]
This should relate to `lease` being an `Option` and that there's no `deserialize_hash` that works for it. Possible solutions could be to implement that or (ideally, at least for consistency) use `serde_as` with `DisplayFromStr` (for which `FromStr` would have to be implemented for `HashDigest`), similarly to how it's done for `Address` ([example](https://github.com/manuelmauro/algonaut/blob/7f20399cf6bb8b33c4a2e7906b83095bc1efdea2/algonaut_model/src/indexer/v2/mod.rs#L775-L777)).
