### ISSUE TITLE
Indexer just launched new version.

### ISSUE THREAD

**Issue by AlterionX** [manuelmauro/algonaut#148]
**Is your feature request related to a problem? Please describe.**
Indexer just got updated. SDK should be correspondingly updated.

**Describe the solution you'd like**
A way to generate the algonaut indexer sdk via the yaml file describing the algorand indexer api.

**Additional context**
Not aure what the update actually entails. I mostly heard about it through the grapevine.

**Comment by AlterionX** [comment]
https://github.com/algorand/indexer/blob/develop/api/indexer.oas3.yml

^ the file

I haven't had a chance to see if algonaut does any of that codegen stuff, so feel free to close if  it does.

**Comment by ivanschuetz** [comment]
I was told that the initial indexer API was generated automatically, but I don't know how. To my knowledge, there's nothing in our code base to do this.

Noting that the generated code had some issues, like unnecessary use of `Box`, non ideal use of `Option` (e.g. when just a `Vec` makes more sense), lack of types (conversion to `Address`), etc. It might be possible to customize it.

**Comment by ivanschuetz** [comment]
@manuelmauro maybe you want to add something - just saw your [OpenApi clients](https://github.com/manuelmauro/algorand-oas-generated-clients) linked in https://github.com/manuelmauro/algonaut/issues/10. It might be worth going through e.g. https://openapi-generator.tech/docs/customization/ to see if it's possible to customize it to match our current more idiomatic API.

**Comment by manuelmauro** [comment]
Yes, I can confirm that I built the current API looking at Algorand's developer documentation and the generated OAS. But I tried to improve the ergonomics addressing issues like those @ivanschuetz highlighted in the previous comment.

**Comment by ivanschuetz** [comment]
Will be solved as part of https://github.com/manuelmauro/algonaut/issues/164 and https://github.com/manuelmauro/algonaut/issues/165
