### ISSUE TITLE
Add GetApplicationAddress from Algorand SDK

### ISSUE THREAD

**Issue by dist1ll** [manuelmauro/algonaut#174]
Would you consider adding a utility function that calculates the address of an application? 

[Snippet from Algorand SDK for reference](https://github.com/algorand/go-algorand-sdk/blob/dc152af6f7acd885e9afc51a74b928a173f456b6/crypto/crypto.go#L718-L728)

I implemented a Rust version with the [sha2 crate](https://crates.io/crates/sha2) and verified its correctness. 

```rust
   15   use sha2::{Digest, Sha512_256};
   [...]
   265  /// Application ID prefix for calculating application account addresses.
   266  static APP_ID_PREFIX: &'static str = "appID";
   267
   268  /// GetApplicationAddress returns the address corresponding to an application's escrow
   269  /// account
   270  fn get_application_address(app_id: u64) -> Address {
   271      let b = app_id.to_be_bytes();
   272      let b = vec![APP_ID_PREFIX.as_bytes(), &b].concat();
   273      let mut hasher = Sha512_256::new();
   274      hasher.update(b);
   275      let mut result: [u8; 32] = Default::default();
   276      result.copy_from_slice(&hasher.finalize()[0..32]);
   277      return Address::new(result);
   278  }
```

**My Question:** If we consider adding it, where should this function be placed? In the Go SDK, it's placed in the crypto module.

**Comment by ivanschuetz** [comment]
There is one!
https://github.com/manuelmauro/algonaut/blob/main/algonaut_core/src/lib.rs#L255

**Comment by dist1ll** [comment]
Thanks!
