### ISSUE TITLE
Implement Logic Crate 

### ISSUE THREAD

**Issue by Sam2much96** [manuelmauro/algonaut#203]
**Is your feature request related to a problem? Please describe.**
Implementing the Logic Crate (In Pyteal it's from algosdk import logic), would allow generating Addresses from App ID's. I noticed that Algonaut has no implementation for this library while porting some Pyteal Code to Rust.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ivanschuetz** [comment]
> generating Addresses from App ID's

That's here:

https://github.com/manuelmauro/algonaut/blob/main/algonaut_core/src/lib.rs#L264

**Comment by Sam2much96** [comment]
Thanks! . Didn't See that earlier.
