### ISSUE TITLE
Is there a way to create a LogicSig?

### ISSUE THREAD

**Issue by epequeno** [manuelmauro/algonaut#21]
I'm following along with this guide: https://developer.algorand.org/docs/features/asc1/stateless/sdks/

I'm at the point where I want to be able to provide arguments to the contract. In order to do this I need to generate a `LogicSig`. This is the example provided for the Go SDK:

```go
// program, err :=  base64.StdEncoding.DecodeString("ASABACI=")
program, err :=  base64.StdEncoding.DecodeString(response.Result)   
var sk ed25519.PrivateKey
var ma crypto.MultisigAccount
var args [][]byte
lsig, err := crypto.MakeLogicSig(program, args, sk, ma)
```
The other official SDKs (java, python, js) all have similar APIs for creating these signatures.

I've taken a look through the various algonaut crates and examples and haven't found anything specific to creating `LogicSig`s. 

It is possible to create these signatures with algonaut currently?

**Comment by i-schuetz** [comment]
All the logic sigs should be functional now in https://github.com/manuelmauro/algonaut/pull/22 
I still need to add a few sanity checks and test more.
