### ISSUE TITLE
QueryAccount limit requests appear to be ignored

### ISSUE THREAD

**Issue by epequeno** [manuelmauro/algonaut#31]
**Describe the bug**
When submitting a query using `QueryAccount` the same number of results are returned regardless of what `limit` is set to.

In this example the first request has no limit requested and the second request attempts to limit the number of results to 1. Irrelevant fields have been omitted.
```rust
    let query_one: QueryAccount = QueryAccount {
        limit: None,
    };
    let accounts: Vec<Account> = indexer_client.accounts(&query_one).unwrap().accounts;

    println!("q1: {}", accounts.len());

    let query_two: QueryAccount = QueryAccount {
        limit: Some(1),
    };
    let accounts: Vec<Account> = indexer_client.accounts(&query_two).unwrap().accounts;

    println!("q2: {}", accounts.len());
```

Which produces these results:

```
q1: 4
q2: 4
```

By comparison, here are what the limit requests look like directly from the indexer:

```
$ curl -s "localhost:8980/v2/accounts" | jq '.accounts|length'
4

$ curl -s "localhost:8980/v2/accounts?limit=1" | jq '.accounts|length'
0

$ curl -s "localhost:8980/v2/accounts?limit=2" | jq '.accounts|length'
1
```
Full example code here: https://gist.github.com/epequeno/e56788eebb7994394be5e5b5123b8a16

**Expected behavior**
Setting `limit` to `None` returns all results. Setting `limit` to `Some(1)` returns 1 result.

**Additional context**
Indexer results when using `limit` appear to be off-by-one, where a limit of `1` returns `0` results. This issue has been reported here: https://github.com/algorand/indexer/issues/516

Tested against a sandbox network running:

```
algod version
8590327808
2.6.0.stable [rel/stable] (commit #8fe22d4e)
go-algorand is licensed with AGPLv3.0
source code available at https://github.com/algorand/go-algorand

Indexer version
2.4.0 compiled at 2021-05-31T22:24:40+0000 from git hash baa014ff63c6638074a04fcea32d4ce647b0dbb8 (modified)
```

**Comment by manuelmauro** [comment]
Thank you for the report! I am looking into this right now.
