### ISSUE TITLE
Alternatives for unwrap when applying builder pattern

### ISSUE THREAD

**Issue by i-schuetz** [manuelmauro/algonaut#32]
See e.g.: https://github.com/manuelmauro/algonaut/blob/v0.2.0/algonaut_transaction/src/builder.rs#L104-L107

We probably should return `Result`. Or maybe add the required fields to `new`. The later would verify at compile time, but we lose the field names, so e.g. `first_valid` and `last_valid` can be accidentally swapped. A possible solution for this could be to pass a new struct that contains only the required fields.

**Comment by dash2507** [comment]
@i-schuetz I like to take this one. I will try to guess what you want here. 

You want to take `genesis_hash, last_valid, sender, txn_type` and put them in separate struct, and pass the struct to Transaction::new()?

**Comment by i-schuetz** [comment]
Thanks for asking @dash2507! I was just listing alternatives. My preference would be to use `Result`. It seems to most clear and simple.

**Comment by manuelmauro** [comment]
I also support the solution using `Result`. In the latter solution, the stuct feels too artificial.

**Comment by i-schuetz** [comment]
https://github.com/manuelmauro/algonaut/pull/60
