### ISSUE TITLE
Traits for algod/kmd/indexer

### ISSUE THREAD

**Issue by ivanschuetz** [manuelmauro/algonaut#48]
Someone asked a while ago for something to be able to mock data to do frontend work. Should we create traits for these services and maybe create a new package (could be here or in a separate repo) that delivers mock data?

**Comment by manuelmauro** [comment]
Sounds interesting, could you post a snippet of how these mocks would look like? Maybe it is something for a separate repo, but we can reference or even use it here.

**Comment by ivanschuetz** [comment]
Hmm just "fake" accounts, transactions etc. I think that we should only add the traits.

**Comment by ivanschuetz** [comment]
Actually, this is a bad idea. These traits should be added by users, if they want to create an abstraction layer over Algonaut.
