### ISSUE TITLE
Potentially confusing "snd" transaction field

### ISSUE THREAD

**Issue by i-schuetz** [manuelmauro/algonaut#49]
`snd` (Sender) has different documentation, depending on whether it's used for a clawback transaction or other transaction types: https://developer.algorand.org/docs/reference/transactions/#asset-clawback-transaction, https://developer.algorand.org/docs/reference/transactions/#common-fields-header-and-type

Allowing users to set `snd` in both `Transaction` and `AssetClawbackTransaction` at the same time seems confusing. Removing it from `AssetClawbackTransaction` loses the clawback-specific documentation. Solutions that come to mind:

- Explain the 2 possible meanings in the the `Transaction`'s `snd` (bit messy)
- Remove `snd` from Transaction and add it to each transaction type with the correct documentation. This would diverge from the way the portal's documentation is structured but it seems correct, as `snd` _as documented in `Transaction`_, is not a common field (the clawback sender doesn't "pay an amount" but withdraws it from one address).

**Comment by manuelmauro** [comment]
Maybe we should opt for a different interface, not exposing `TxtBuilder` but incorporating the common fields in the other builders. This would also clarify fields like `amount` and `asset_amount`.

**Comment by i-schuetz** [comment]
That's a good idea! But it still leaves us with the problem in `Transaction`. On further thought, moving `snd` down to the types, because of possible additional documentation, is weird. The signer is common and should stay in `Transaction`.

I think that the correct solution would be to have the transaction types contain contain the common fields (via a nested struct and/or a trait), instead of being contained in the transaction. This way we can adapt the common fields to the individual use cases.

This refactoring might be overkill though (it's only documentation and one field), so I'd lean for now towards the "bit messy" option where we just use the `Transaction`'s `snd` field and document the possible additional meanings on it. The user will not interact much with this, but with the builders, which we'd structure as you described.

Tangentially: Do we really need to use builder pattern? We don't have mutually exclusive fields or a lot of optionals, on the other side we make the user check the docs to see what's required or optional and deal with `Result` (or unwrap). With a simple struct or function they see immediately what's required and everything is checked at compile time.

**Comment by i-schuetz** [comment]
The "correct solution" I described actually could solve everything: we could convert `Transaction` to an enum, where the cases would be similar to the builders you're describing, and remove the builders.. The user would directly create these cases:

```rust
let txn = Transaction::Payment(Payment { sender: ..., fee: ..., amount: ... });
// or with a helper function that returns Transaction::Payment
// let txn = Transaction::pay(sender, fee, amount, ... );
account.sign_transaction(txn);
...
```
And we would map this enum directly to `ApiTransaction`.

**Comment by manuelmauro** [comment]
Good point about the builders, they currently feel just a "cosmetic" layer. To actually make sense the `Transaction` builder should be kind of a state automaton that exposes different methods depending on the kind of transaction it is building.

**Comment by i-schuetz** [comment]
How about:

1) Move `sender` down to the transaction types in the builders and in `Transaction`, to be able to document/name them differently. The shared `snd` field is basically an API implementation detail, so it stays only in `ApiTransaction`.

2) Set required fields in the builder's `new`.

3) Add suggested transaction params (similar to the [Go SDK](https://github.com/algorand/go-algorand-sdk/blob/26eff5c93fee3b0a2e5b84afbb271de5e532bf5c/client/v2/algod/transactionParams.go#L20-L28)) to reduce verbosity:

```rust
let sp = algod.suggested_transaction_params().await;
TxnBuilder::with_params(sp)
// overwrite
TxnBuilder::with_params(SuggestedParams{ sp.fee + 1000, ..sp })
```


Combined:

```rust
TxnBuilder::with_params(sp)
    .payment(Pay::new(sender, receiver, amount).close_remainder_to(receiver).build())
    .build()
```

We can instantiate the builder in `payment`:
```rust
TxnBuilder::with_params(sp)
    .payment(sender, receiver, amount).close_remainder_to(receiver).build()
    .build()
```

**Comment by i-schuetz** [comment]
To clarify, I think that setting the nested builder is a bit clearer to the user. We could do something like this:

```rust
let tx = TxBuilder::new(sp)
    .payment(sender, receiver, amount) // transition to tx + payment state
    .close_remainder_to(address)
    .build();
```

It reads nicer, but after you call `pay` you can't call `TxBuilder` functions anymore, which isn't intuitive. It can be possible e.g. adding the `TxBuilder` functions to the pay composite but this seems overcomplicated.

**Comment by manuelmauro** [comment]
Yes, I agree. The nested one seems clearer. Thanks!
