### ISSUE TITLE
Improve error messages from API calls

### ISSUE THREAD

**Issue by manuelmauro** [manuelmauro/algonaut#5]
Currently the error messages received from the APIs are lost and only the status code is kept. Improve the experience returning additional information.

**Comment by manuelmauro** [comment]
This issue is a bit more involved than the brief description I came up with, I will try to expand.
The current approach to API calls is something like this:
```rust
pub fn account_information(&self, address: &str) -> Result<Account, AlgorandError> {
        let response = self
            .http_client
            .get(&format!("{}v2/accounts/{}", self.url, address))
            .headers(self.headers.clone())
            .header(AUTH_HEADER, &self.token)
            .send()?
            .error_for_status()?
            .json()?;

        Ok(response)
    }
```
using `error_for_status()` in the case the API response contains an error code we just ignore the body and report the status code. The problem with this approach is that we lose some very insightful information returned by Algorand's APIs which is packed in a body like this https://developer.algorand.org/docs/reference/rest-apis/algod/v2/#errorresponse

It would be ideal to return an error containing information relative to the `data` and `message` field.

`reqwest` offers an easy way to do this, but we must be wary of code duplication when implementing it.
https://docs.rs/reqwest/0.11.3/reqwest/blocking/struct.Response.html#implementations

```rust
let resp = reqwest::blocking::get("http://httpbin.org/get")?;
if resp.status().is_success() {
    println!("success!");
} else if resp.status().is_server_error() {
    println!("server error!");
} else {
    println!("Something else happened. Status: {:?}", resp.status());
}
```

**Comment by i-schuetz** [comment]
The extension I added does something along those lines: https://github.com/manuelmauro/algonaut/blob/e46b8eb8d06e88d10d9f7bc88c2310a055263009/algonaut_client/src/extensions/reqwest.rs#L10-L26

It also keeps the caller side simple, by just having to replace `error_for_status` with `http_error_for_status`.

I'm delivering the reqwest error with the parsed message in a [new struct](https://github.com/manuelmauro/algonaut/blob/e46b8eb8d06e88d10d9f7bc88c2310a055263009/algonaut_client/src/error.rs#L30-L33). If there's no error message, the message is empty.

I didn't add the data field as it didn't follow from the initial task and it's unclear what it is. Assume it's context dependent? If yes, we can just add a string/json field to `HttpError` and interpret it in the individual api calls (e.g. in the `account_information` function you posted)?

**Comment by manuelmauro** [comment]
Sorry, my fault! Your pull request is exactly what we need! I am gonna go carefully through the code and review it. We can postpone the management of the `data` field to another issue.

**Comment by i-schuetz** [comment]
Np! want to add that I considered mapping  the `reqwest` error to a new domain error, to decouple `AlgorandError` from `reqwest`, but that's probably out of scope for this PR too (`reqwest` can return non-http errors so we'd have to abstract over that / add equivalent types).

**Comment by manuelmauro** [comment]
Thanks for the comment, I am not pleased at all by the current state of error management in the crates. Feel free to open any issue concerning the design of our errors such as the one you just mentioned, it would be nice to discuss new ideas.
